# set this to null to log to STDOUT instead
log_path: /var/log/botologist.log
# available log levels: debug, info, warn, error
log_level: debug

# the server to connect to
server: irc.quakenet.org:6667

# the nick to use
nick: botologist

# the username (ident)
username: botologist

# the real name - shows up in /whois
realname: botologist

# hosts of global admin users
admins:
  - my.host.com

# hosts of banned users
bans:
  - banned.host.com

# plugins that are enabled in every channel
global_plugins:
  - default
  - url

# channels the bot joins on connect. since the character starts a comment in
# YAML, wrap the channel name in quotes or leave out the #. each channel can
# have their own set of admins and plugins which only apply to that channel.
channels:
  - channel: '#mychannel'
    admins:
      - some.other.host.com
    plugins:
      - streams
  - channel: '##otherchannel'
    plugins:
      - conversion

# uncomment these lines to enable the !mumble command
#mumble:
#  address: my.host.com
#  port: 64738
#  password: p4sSw0rD

# uncomment these lines if you want to use the twitter plugin
#twitter_api:
#  consumer_key: 'consumer_key'
#  consumer_secret: 'consumer_secret'
#  access_token: 'access_token'
#  access_token_secret: 'access_token_secret'

# if you want to run a HTTP server for webhooks, uncomment these lines
#http_host: localhost
#http_port: 9123

# if you want error reports sent via real email, uncomment these lines.
# usually, if you have an exim instance running on your server, setting this to
# a username on the server instead of an actual e-mail address will send it to
# /var/mail/$USER. if you want to send to the user running the bot process,
# set admin_email: null
#admin_email: myname@mydomain.com
#mail_from: ircbot@mydomain.com

# mail is sent via sendmail. customize the bin path and args here:
#sendmail_bin: /usr/sbin/sendmail
#sendmail_args: -t -oi

# openweathermap is used for the !weather command
# openweathermap_apikey: ...
